const events = [
  {
    _id:'1',
    title: 'Seattle New Years Eve Party 2023',
    image: '/images/eveparty.jpg',
    price: 155,
    description: `Join us for the most upscale New Year's Eve Party in Seattle, Gatsby's Penthouse! 4hr prepaid bar, top DJs, casino games with prizes & more!`,
    location: 'King Street Ballroom & Perch 255 S King St Seattle, WA 98104',
    dateTime: 'Sat, Dec 31, 2022, 9:00 PM - Sun, Jan 1, 2023, 1:30 AM PST',
    countInStock: 10  
  },
  {
    _id:'2',
    title: `Gala Galactica: New Year's Eve`,
    image:'/images/gala.jpg',
    price: 69.38,
    description:'We welcome you to explore the dancefloor glory of Gala Galactica. Express your divinity. Let the universe love you.',
    location:'House of Yes 2 Wyckoff Avenue Brooklyn, NY 11237',
    dateTime:'Sat, Dec 31, 2022, 10:00 PM - Sun, Jan 1, 2023, 4:00 AM EST',
    countInStock:15,
  },
  {
    _id:'3',
    title: 'Seattle Tech Career Fair: Exclusive Tech Hiring Event',
    image:'/images/tech.jpg',
    price: 10,
    description:'Tech Career Fair focus on helping companies achieve their diversity and inclusivity initiative with more diverse non-traditional candidates',
    location:'Online Seattle, WA 98101',
    dateTime:'Fri, December 16, 2022, 9:00 AM - 12:00 PM PST',
    countInStock: 100,
  },
  {
    _id:'4',
    title: 'Ballard Cocktail Trail',
    image:'/images/ballard.jpg',
    price: 45,
    description:'Enjoy handcrafted cocktails while exploring boutique shops at the Ballard Cocktail Trail on Friday, December 9th, from 6 - 9 pm!',
    location:'2212 NW 56th St 2212 Northwest 56th Street Seattle, WA 98107',
    dateTime:'Fri, December 9, 2022, 6:00 PM - 9:00 PM PST',
    countInStock:5,
  },
  {
    _id:'5',
    title: 'Oddities Flea Market New York City',
    image:'/images/flea.jpg',
    price: 22.85,
    description:'Oddities Flea Market is thrilled to welcome you to the Metropolitan Pavilion in Manhattan this winter!',
    location:'Metropolitan Pavilion 125 West 18th Street New York, NY 10011',
    dateTime:'Sat, December 10, 2022, 11:00 AM - 7:00 PM EST',
    countInStock: 15,
  },
  {
    _id:'6',
    title:'Gingerbread Jamboree (Festive Gingerbread House Decorating Party)',
    image:'/images/gingerbread.jpg',
    price:94.90,
    description:'Join us for a festive downtown community gingerbread house decorating event filled with fun, creativity, music and surprises!',
    location:'28-42 Trinity Place, New York, NY 10006',
    dateTime:'December 3, 2022 / 10:00 am - 1:00 pm',
    countInStock: 50,
  },
]
export default events